### PR TITLE
🎉 Check for WScript.exe

### LINKED ISSUE #1812: Error on trying to edit preferences
When I go to Menú --> Edit --> Preferences, I'm getting the following message:

Error: 'module' is not defined.

Please see the attached image for more info.
Thanks.
image

-

Hyper 1.3.2
Electron 1.4.16
win32 x64 6.1.7601

### PR DESCRIPTION
**Pull request by albinekb**
This is my proposed solution for handling #1812

We could add a key in the config for setting the editor, but I think that's a bad idea. Better to teach the users to set the correct app for .js files :) maybe put an alert/dialog with a link on how to do it.

At least this will let people open their config without errors, and we can think about how we can make this better in the future

Fixes #1812 https://github.com/zeit/hyper/issues/1810 https://github.com/zeit/hyper/pull/1784#issuecomment-301396453 https://github.com/zeit/hyper/issues/1854

### CODE REVIEW

File: app/menus/menus/edit.js [hunk 1]
```diff
@@ -52,7 +51,7 @@ module.exports = function () {
         label: 'Preferences...',
         accelerator: accelerators.preferences,
         click() {
-          shell.openItem(confPath);
+          openConfig();
```
Comment (chabou) [inline app/menus/menus/edit.js]: Can you use the same `onpenConfig()` function here: https://github.com/zeit/hyper/blob/3c1f359198a71c6946f326bfda3e53f612ade23e/app/menus/menus/darwin.js#L21 ?

**Comment by chabou** [comment]
I really love this solution! ❤️

File: app/menus/menus/edit.js (hunk 1 above)
Comment (albinekb) [inline app/menus/menus/edit.js]: yep fixed @chabou 👌

File: app/config/open.js [hunk 2]
```diff
@@ -0,0 +1,33 @@
+const {shell} = require('electron');
+const {confPath} = require('./paths');
+
+module.exports = () => Promise.resolve(shell.openItem(confPath));
```
Comment (tnguyen14) [inline app/config/open.js]: Why are there 2 `module.exports` in this file?

Comment (albinekb) [inline app/config/open.js]: since we want to have a different module on windows compared to others

File: app/config/open.js [hunk 3]
```diff
@@ -0,0 +1,33 @@
...
+  });
+
+  // Windows opens .js files with  WScript.exe by default
+  // If the user hasn't set up an editor for .js files, we fallback to notepad.
+  const canOpenNative = () => new Promise((resolve, reject) => {
+    exec('ftype JSFile', (error, stdout) => {
+      if (error) {
+        reject(error);
+      } else if (stdout && stdout.includes('WScript.exe')) {
+        reject(new Error('WScript is the default editor for .js files'));
```
Comment (tnguyen14) [inline app/config/open.js]: If `WScript.exe` exists, this will throw an error, which will then open the conf file with notepad? I thought the idea is to use `WScript.exe` if it exists?

Comment (ppot) [inline app/config/open.js]: @tnguyen14 No, `WScript.exe` run the file instead of editing it.

Comment (albinekb) [inline app/config/open.js]: It will check if your default editor is set to WScript.exe, if it is , it will use notepad.exe, since WScript.exe isn't an editor

Comment (tnguyen14) [inline app/config/open.js]: Ah. I see. I understand now. Thank you for the clarification. I was confused by this comment: `Windows opens .js files with  WScript.exe by default`

**Comment by Stanzilla** [comment]
Does not work on Windows, even though a default program other than WScript is set for .js, it opens notepad.

**Comment by dave-irvine** [comment]
I've got a bit of a problem here in that you can manually change filetype associations like this:

    ftype JSFile=notepad.exe %1 %*

but then hyper won't start any more. So without a configuration option to change what editor opens the configuration file, I'm stuck with notepad.

Any suggestions?
