### PR TITLE
quickEdit support

### LINKED ISSUE #2260: [v2] copyOnSelect and quickEdit not working with v2
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

* **OS version and name**: ubuntu linux 16.04 64x
* **Hyper.app version**: canary branch ([tag 2.0.2](0502bbfc79d5421e0a6758ea671b7bb19d76c1cb)) - both custom build and release.
* **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/mojoaxel/a55766b1b6efc1f1802d1e43dab96919

## Issue
* [ ] **copyOnSelect** is not working with the current v2.0.2. Selecting a text is not copying it to the clipboard.
* [ ] **quickEdit** is not working with the current v2.0.2. It looks like right-click events are not handled at all.

### PR DESCRIPTION
**Pull request by derrickpelletier**
tested on mac, ubuntu 16.04, windows 10

closes #2260, #2318 

Note that this should close #2348, which is the same functionality, very slightly different implementation. I didn't intend to duplicate their effort, but @chabou asked me to submit this (in https://github.com/zeit/hyper/pull/2390#issuecomment-339148926)

As far as I know, and based on a simple test in windows command prompt, this works as expected:
- Select text
- right click anywhere to copy the selection
- selection clears
- right click anywhere to paste

If there are any nuances to quick-edit beyond that, I'm not aware of them, but even still this is probably enough for a first iteration at the very least.

### CODE REVIEW

File: lib/components/term.js [hunk 1]
```diff
@@ -131,11 +131,21 @@ export default class Term extends PureComponent {
...
+  onMouseUp(e) {
     // handle copying selected text
     if (this.props.copyOnSelect && this.term.hasSelection()) {
       clipboard.writeText(this.term.getSelection());
     }
+
+    // handle quickEdit copy/paste with right click
+    if (this.props.quickEdit && e.button === 2) {
+      if (this.term.hasSelection()) {
+        clipboard.writeText(this.term.getSelection());
```
Comment (albinekb) [inline lib/components/term.js]: Won't this be run twice? if you have both `quickEdit` and `copyOnSelect` activated?
can't we just change the if here https://github.com/zeit/hyper/pull/2392/files#diff-268710614c2274f611be667a5f72bb13R136

```
if ((this.props.copyOnSelect || this.props.quickEdit && e.button === 2) && this.term.hasSelection()) {
```
Otherwise it will be copied twice which could be a problem
🤔

Comment (derrickpelletier) [reply lib/components/term.js]: Ah yeah, if you select text _and then_ right click, the right click would copy the same text twice. It still works but you're right, unnecessary.

That condition you suggested isn't enough, because in the quickEdit case, it needs to clear the selection after copying. I modified it to just do one or the other, thoughts?

Comment (albinekb) [reply lib/components/term.js]: Looks good to me! @derrickpelletier 👍

**Comment by Stanzilla** [comment]
Tested and works well!

**Comment by chabou** [comment]
🙏  Thank you @derrickpelletier
