### PR TITLE
fix undefined fish shell match

### LINKED ISSUE #1513: Issues with plugins on Hyper 1.2.0 & 1.2.1
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: `10.12.3 macOS Sierra`
- **Hyper.app version**: `1.2.1`
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: `Default`
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: `N/A`
- **The issue is reproducible in vanilla Hyper.app**:  `Is Vanilla`

## Issue
Getting `Error updating plugins.` even without any plugins. It says to check for `~/.hyper_plugins/npm-debug.log` but no such file exists.

Seems to be having issues with downloading plugins as well. Getting `Plugin "name" failed to load (Cannot find module '/Users/henrik/.hyper_plugins/node_modules/name')`

Tried installing fresh, simply reinstalling as well. Still remains.

### PR DESCRIPTION
**Pull request by henrikdahl**
Fixes #1513 

Basically if you have no shell specifically set in config then `const shell` is set to `undefined` which match fails on because it can't match on `undefined`.

This commit matches against `cfgShell` instead.

### CODE REVIEW

File: app/plugins.js [hunk 1]
```diff
@@ -241,7 +241,7 @@ function install(fn) {
       posix: 'npm prune && npm install --production'
     };
     // determine the shell we're running in
-    const whichShell = shell.match(/fish/) ? 'fish' : 'posix';
+    const whichShell = cfgShell.match(/fish/) ? 'fish' : 'posix';
```
Comment (albinekb) [inline app/plugins.js]: Sure we don't want to check `shell` as a fallback to `cfgShell`?  🤔  Have not had time to check the full code, but tested this branch with fish and it seems to work as expected

Comment (albinekb) [inline app/plugins.js]: for extra ⭐️  i would rename this variable to `shellType` to be more descriptive

Comment (albinekb) [inline app/plugins.js]: Maybe change this to:
```js
const whichShell = (typeof cfgShell === 'string' && cfgShell.match(/fish/)) ? 'fish' : 'posix';
```
To guard for values that aren't strings

**Comment by zsol** [comment]
I just ran into this. After fixing it for myself I realized this is already addressed in `master` but not in the latest release. Kind of a turnoff for a completely new user to see this right after installing the latest release for the first time. Maybe cut a hotfix release?
