### PR TITLE
Add support for composed chars and fix issues with "foreign" keyboard layouts

### LINKED ISSUE #29: Special characters and foreign keyboard not displayed correctly
So I use Spanish ISO keyboard (like this one: http://g01.a.alicdn.com/kf/HTB1iOQ8HVXXXXaeXpXXq6xXFXXXd/Spanish-Euro-Keyboard-Cover-Protector-for-MacBook-Air-11-11-6-Inch-European-ISO-Keyboard-Spain.jpg_640x640.jpg), and it is impossible to type some characters.

For example, "special" characters like ¿¡· are displayed like this: <00c2><00bf><00c2><00a1><00c2><00b7>, same with the ñ.

And other keyboard combinations are just impossible to type, my biggest issue is **~**, since I need to type _Alt + ñ_ but it just doesn't appear. Same issue with any letter with an accent (á, ö, â, etc).

I'm using zsh, if it matters.

### LINKED ISSUE #66: can't write accented characters on a portuguese keyboard
This sentence here

> Note that composed characters (those that require multiple keystrokes) are not currently supported by this mode.

https://chromium.googlesource.com/apps/libapps/+/HEAD/nassh/doc/FAQ.md#How-do-I-enter-accented-characters

suggests this is not possible using `hterm`

any has any idea how to solve this?

### LINKED ISSUE #466: Can't type ~ character
Hello guys,

I can't type the ~ character in Hyperterm in 0.7.1 as in the previous versions. Could someone help me? Thank you so much!

### LINKED ISSUE #518: Can't type " or ' on US Int
When i am typing with the `U.S. International - PC` layout of my mac i cant type the caracter `'` or `"`  neither can i type `~`  nor ` ` ` though. :(  This is kind of a dealbreaker for me.

### LINKED ISSUE #579: Entering a "~" / "`" symbol does not work with German keyboard
I have a iMac with a German keyboard. Entering the tilde symbol using the normal key shortcut `alt+n` does not work. The same with the backtick symbol "`" itself which is placed after the`ß` symbol.

There is also some issue with the dollar sign (shift+3). This jumps a word to the beginning instead of entering the symbol.
## 

HyperTerm 0.7.1
Electron 1.2.8
darwin x64 15.6.0

### PR DESCRIPTION
**Pull request by matheuss**
kapture 2016-11-16 at 15 22 03

## Summary

This PR introduces an attempt to fix all the following issues:

Major:
* **Users on some "foreign" keyboard layouts (Portuguese and Norwegian, for example) weren't able to type characters like `~`, `'`, `"` and so on**
* **Characters that need a composition event couldn't be typed – `á`, `é`, `ü` and so on**

Minor:
* After the bell, the cursor would go back to a `BLOCK` – #674 
* Selecting pane on blurred window requires two clicks – #861 

Other than that, this changes _should_ fix the following:
* Some people can't paste unless Hyper receives a click – #897
* Issues with copy-pasting – #484 #479 

## Prebuilt binaries

Check [here] for a `.dmg`, a `.exe`, a `.deb` and a `.rpm` 😄

## How

The work I did on this PR was just an improvement on top of @rauchg's [method] – huge thanks to him for developing it! Also, thanks @nfcampos for your work on #214 🙌 

We inject a `hyper-caret` div that has `contenteditable="true"` inside `hterm`'s cursor. With that, we're able to show an intermediate state of composition – so you can see (and type) the character you want. 
When the char is ready, `hterm` automatically captures it – that means we only need to worry about showing that intermediate state.

Closes #29; Closes #66; Closes #466; Closes #518; Closes #579;

[method]: https://github.com/zeit/hyper/commit/6ef13a2c3b525910250bc86f252eb3dc5f0f8744
[here]: https://drive.google.com/drive/folders/0BzynZtaOcjwMNGVaVlFXeFBwdFE?usp=sharing

### CODE REVIEW

**Comment by rauchg** [comment]
👊

**Comment by sergiovilar** [comment]
:+1:

**Comment by nfcampos** [comment]
great to see this finally resolved! :)

**Comment by kauegimenes** [comment]
Finally i can start using hyper!

**Comment by YuriBrunetto** [comment]
Great work, everybody!
👏 👏 👏 👏 👏 👏

**Comment by bdc-stripe** [comment]
zomg this makes me so happy 😍

**Comment by frdmn** [comment]
Well done! 👍

**Comment by albinekb** [comment]
@jbergstroem there isn't the hterm code is hosted and maintained over at googles [git](https://chromium.googlesource.com/apps/libapps/+/HEAD/hterm)

But i think it's an easy fix and even possible to do just by some more prototype hacking 😏 
I'll have a look later this week.

Great job @matheuss

**Comment by matheuss** [comment]
@jbergstroem there's already a `setTimeout` in `hterm`'s code 😄 I just created another one to add that call 👌 Other than that, the bell will not play more than once per second (guaranteed by `hterm`'s code), so we're good 👌 

Thank you @albinekb 🙌

**Comment by jbergstroem** [comment]
@matheuss thanks for elaborating.

File: lib/hterm.js [hunk 1]
```diff
@@ -212,6 +151,102 @@ hterm.ScrollPort.prototype.setBackgroundColor = function () {
...
+};
+
+// fixes a bug in hterm, where the cursor goes back to `BLOCK`
+// after the bell rings
+const oldRingBell = hterm.Terminal.prototype.ringBell;
+hterm.Terminal.prototype.ringBell = function () {
+  oldRingBell.call(this);
+  setTimeout(() => {
+    this.restyleCursor_();
+  }, 200);
```
Comment (rauchg) [inline lib/hterm.js]: We need to add some sort of `if` check or clear this timeout somewhere :P

Comment (matheuss) [inline lib/hterm.js]: @rauchg I'm not sure if it's necessary – it's just an extension of the timeout that `hterm` creates:

```javascript
hterm.Terminal.prototype.ringBell = function() {
  this.cursorNode_.style.backgroundColor =
      this.scrollPort_.getForegroundColor();

  var self = this;
  setTimeout(function() {
      self.cursorNode_.style.backgroundColor = self.prefs_.get('cursor-color');
    }, 200);
...
```

Comment (matheuss) [inline lib/hterm.js]: What do you think?

**Comment by jbergstroem** [comment]
@albinekb that means bug tracker lives here: https://bugs.chromium.org/p/chromium/issues/list

**Comment by kentcdodds** [comment]
Hmmm... Was this supposed to resolve the emoji issues? I did a fresh download/install and it appears to still not be working well for me... Am I missing something?

hyper

**Comment by noamcore** [comment]
This pull request has not been released yet.

**Comment by danilomiranda** [comment]
Great man! Thank you very much!

**Comment by karlpokus** [comment]
Is [1.0.0](https://github.com/zeit/hyper/releases/tag/1.0.0) supposed to have support for å, ä and ö? I'm on 1.0.0.1303 and it does not work.

**Comment by noamcore** [comment]
@karlpokus yes.

screen shot 2016-12-13 at 4 05 22 pm

**Comment by karlpokus** [comment]
@noamcore Wierd. Still don't work. My <kbd>ö</kbd> returns `(arg: 6)`. Is my keyboard f**ked?

**Comment by jbergstroem** [comment]
@karlpokus works for me too. Perhaps check your locale env?

**Comment by karlpokus** [comment]
@jbergstroem 
```
~ $ locale
LANG="sv.UTF-8"
```
OS X 10.11.5

**Comment by jbergstroem** [comment]
@karlpokus shouldn't that be sv_SE.UTF-8?

**Comment by jmml97** [comment]
hi! I have the same problem as @karlpokus I cannot type á or ñ on 1.0. It returns (arg: 2). What is wrong? My locale shows `LANG="es.UTF-8"`. Tried changing it to `LANG="es_ES.UTF-8"` but it didn't work...

**Comment by noamcore** [comment]
```
$ locale
LANG=
LC_COLLATE="C"
LC_CTYPE="UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```

screen shot 2016-12-15 at 1 19 02 pm

Which keyboard layout are you using?

**Comment by negatron99** [comment]
On Windows 10, attempting to type Japanese characters using the IME. 

When typing the first character, the IME immediately disables itself (a cross in it's notification icon) and only the next character is outputted to the terminal. The IME then appears to enable itself (Hiragana symbol) but it continues this cycle of being disabled and enabled.

**Comment by noamcore** [comment]
@negatron99 Japanese characters **are not working** even in macOS.

I tried right now, with no success.

**Comment by alayii** [comment]
Chinese input method also not working in macOS 10.12.2

if using macOS Pinyin input method, when I type `a`, nothing appeared in terminal, type `a` again, character `a` appeared, I cannot type spacebar to choose chinese character, and  candidate box always blink.

if using [Squirrel](https://github.com/rime/squirrel) input method, every typing will directly send a chinese character to terminal, cannot choose.

and character width is not right.

**Comment by karlpokus** [comment]
@jbergstroem Yes it should.
```
# hyper
$ locale
LANG="sv.UTF-8"

# terminal
$ locale
LANG="sv_SE.UTF-8"
```
Are they suppose do differ?
@noamcore I am using `Svensk - Pro` keyboard layout.

**Comment by jbergstroem** [comment]
@karlpokus you should set it (correctly) as part of your shell init. Terminal probably does that for you.

**Comment by karlpokus** [comment]
@jbergstroem So you're saying this setting is on the user - not a bug in hyper? or a temp solution?

**Comment by jbergstroem** [comment]
@karlpokus setting a proper locale should be done in the shell, not in the terminal. Some terminals does it for you though. Anyway, I don't even know if this fixes it for you :)

**Comment by karlpokus** [comment]
@jbergstroem Didn't know the terminal on macOS wasn't a shell :/

Anyways. `sv.UTF-8`is not a valid option it seems and maybe hyper should consider changing it?
```
# in both terminal and hyper
~ $ locale -a | grep sv -i
sv_SE
sv_SE.ISO8859-1
sv_SE.ISO8859-15
sv_SE.UTF-8
```

**Comment by kleinfreund** [comment]
@karlpokus If the wrong value `sv.UTF-8` is causing your issue then this is on you to change, not Hyper.

**Comment by karlpokus** [comment]
@kleinfreund cool. No Problemo. FWIW I can't remember changing this value myself so I thought this might be a bug in hyper considering my terminal got it right.

**Comment by jmml97** [comment]
Typing `locale` on macOS terminal shows me `es_ES.UTF-8` but on Hyper I get `es.UTF8`

**Comment by jmml97** [comment]
Doing what @karlpokus says above resolves the problem.

**Comment by Simon-L** [comment]
Hi, I've done my best to help with improving this as I agree it's an absolute maximum priority issue.
All my research was done on Linux (Mint 18 Cinnamon) set to **French** language and without looking at Hyper's code, *at least for now*.

Here is what I have:
On **Debian** based distros, as per [Debian wiki](https://wiki.debian.org/Locale#Standard), one place to look at would be `/etc/defaults/locale`:
```
$ cat /etc/defaults/locale
#  File generated by update-locale
LANG="fr_FR.UTF-8"
```
More specific tools exist on distros using `systemd`, ie. `localectl`:
```
$ localectl
fr_FR.UTF-8
```
`localectl` provides a reliable output inside Hyper, as opposed to `locale` which is set to a wrong value inside Hyper and a correct one in gnome-terminal and in TTYs (ctrl+alt+F1...+F2 etc.)

I have then looked at Node packages used for locale/intl'ization, though they seem to be using LC and LANG environment variables: https://github.com/sindresorhus/os-locale/blob/master/index.js#L9
It should be noted that Node obviously gets it right outside of Hyper: `process.env.LANG` has the correct value.

It seems Hyper is getting the locale value from the wrong source. I'm still looking for gnome-terminal's way of doing this. Editing either .bashrc or .bash_profile fixes it but I believe that similarly to the many other applications one is running, Hyper should get it right from the start.
